My_NewsSite/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLayrer;

namespace My_NewsSite.Controllers
{
    public class NewsController : Controller
    {
        My_SiteContext db = new My_SiteContext();

        private IPageGroupRepository pageGroupRepository;
        private IPageRepository pageRepository;
        private IPageCommentRepository pageCommentRepository;

        public NewsController()
        {
            pageGroupRepository = new PageGroupRepository(db);
            pageRepository = new PageRepository(db);
            pageCommentRepository = new PageCommentRepository(db);
        }

        // GET: News
        public ActionResult ShowGroups()
        {
            return PartialView(pageGroupRepository.GetGroupsForView());
        }

        public ActionResult ShowGroupsInMenu()
        {
            return PartialView(pageGroupRepository.GetAllGroups());
        }

        public ActionResult TopNews()
        {
            return PartialView(pageRepository.TopNews());
        }

        public ActionResult LatesNews()
        {
            return PartialView(pageRepository.LastNews());
        }

        [Route("Archive")]
        public ActionResult ArchiveNews()
        {
            return View(pageRepository.GetAllPage());
        }

        [Route("Group/{id}/{title}")]
        public ActionResult ShowNewsByGroupId(int id, string title)
        {
            ViewBag.name = title;
            return View(pageRepository.ShowPageByGroupId(id));
        }

        [Route("News/{id}")]
        public ActionResult ShowNews(int id)
        {
            var news = pageRepository.GetPageById(id);
            if(news == null)
            {
                return HttpNotFound();
            }
            news.Visit += 1;
            pageRepository.UpdatePage(news);
            pageRepository.Save();
            return View(news);
        }

        public ActionResult AddComment(int id, string name , string email , string comment)
        {
            PageComment Addcomment = new PageComment() 
            {
                 CreateDate = DateTime.Now,
                 PageID = id,
                 Comment = comment,
                 Email = email,
                 Name = name
            };
            pageCommentRepository.AddComment(Addcomment);
            return PartialView("ShowComments",pageCommentRepository.GetCommentByNewsId(id));
        }

        public ActionResult ShowComments(int id)
        {
            return PartialView(pageCommentRepository.GetCommentByNewsId(id));
        }
    }
}

My_NewsSite/Views/Shared/_DefaultLayout.cshtml
<!DOCTYPE html>
<html class="no-js" dir="rtl" lang="fa-IR">
<head>
    <meta charset="UTF-8">
    <title> سایت خبری برنامه نویسی </title>
    <base href="">
    <meta name="googlebot" content="index,follow">
    <meta name="robots" content="noodp,noydir">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/Content/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/Content/css/bootstrap-rtl.min.css">
    <link rel="stylesheet" type="text/css" href="/Content/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/Content/css/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="/Content/css/style.css">
    <link href="https://cdn.rawgit.com/rastikerdar/sahel-font/v1.0.0-alpha23/dist/font-face.css" rel="stylesheet" type="text/css" />
    <script src="/Content/js/jquery.min.js"></script>
</head>
<body class="rtl" style="font-family: Sahel,sans-serif;">
    <script src="/Content/js/modernizr.js"></script>

    <!-- Top Menu -->
    <div class="top-menu">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-5">
                    <ul>
                        <li><a href=""><i class="fa fa-home"></i></a></li>
                        <li><a href=""><i class="fa fa-question-circle"></i></a></li>
                        <li><a href=""><i class="fa fa-envelope"></i></a></li>
                    </ul>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-7">
                    <span>امروز : @DateTime.Now.ToShamsi()</span>
                </div>
            </div>
        </div>
    </div>
    <!-- End Top Menu -->
    <!-- header -->
    <header class="main-header">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <a href="" class="logo"><img src="/Content/img/log.png" alt="" title=""></a>
                    <div class="left-side">
                        <br />
                        <h1><a href="">سایت خبری برنامه نویسی</a></h1>
                        <h2> پایگاه اطلاع رسانی و خبری</h2>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
            <form action="/Search" method="get" class="border-radius">
                <input class="border-radius" type="text" name="q" placeholder=" دنبال چی میگردی؟! ">
                <button><i class="fa fa-search"></i></button>
            </form>
        </div>
            </div>
        </div>
    </header>
    <!-- End Header -->
    <!-- menu -->
    <nav class="main-menu">
        <div class="container">
            <span><i class="fa fa-th-list"></i></span>
            <ul>
                <li><a href="/"> صفحه اصلی </a></li>
                <li><a href="/Archive"> آرشیو خبرها </a></li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li><a href=""> @User.Identity.Name خوش اومدی. </a></li>
                    <li><a href="/account/signout"> خروج از حساب </a></li>
                }
                else
                {
                    <li><a href="/account/login"> ورود به سایت </a></li>
                }

                <li>
                    @Html.Action("ShowGroupsInMenu", "News")
                </li>
            </ul>
        </div>
    </nav>
    <!-- End menu -->
        <div class="container margin-top-30">
            <div class="row">

                <aside class="col-md-4 col-sm-12 col-xs-12 pull-right">

                    @if (User.Identity.IsAuthenticated)
                    {
                        <div class="thumbnail">
                            <section class="last-news-side border-radius">
                                <header><i class="icons icon-star"></i> <h3>بخش مدیرت تبلیغات</h3></header>
                                <ul>
                                    <li>
                                        <a href="/Admin/PageGroups">مدریت گروه ها</a>
                                    </li>

                                    <li>
                                        <a href="/Admin/Pages">مدریت خبرها </a>
                                    </li>
                                </ul>
                            </section>
                        </div>
                    }

                    @Html.Action("ShowGroups", "News")
                    <!-- most views news -->
                    @Html.Action("TopNews", "News")
                    <!-- end most views news -->
                </aside>


                <div class="col-md-8 col-sm-12 col-xs-12 ">

                    @RenderBody()

                </div>
            </div>
        </div>

        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-12 col-xs-12">
                        <section class="access-links">
                            <header> دسترسی سریع </header>
                            <ul>
                                <li><a href="/"> صفحه اصلی </a></li>
                                <li><a href="/Archive"> آرشیو خبرها </a></li>
                                <li><a href="/account/login"> ورود به سایت  </a></li>
                            </ul>
                        </section>
                    </div>
                    <div class="col-md-5 col-md-offset-1 col-sm-12 col-xs-12">
                        <div class="socials">
                            <span> شبکه های اجتماعی  سایت</span>
                            <a href="https://github.com/barnamenevisi-info"><i class="fa fa-github"></i></a>
                            <a href="https://www.instagram.com/barnamenevis.info/?hl=en"><i class="fa fa-instagram"></i></a>
                            <a href="https://t.me/Theres_no_such_thing_as_security"><i class="fa fa-paper-plane"></i></a>
                            <div class="clearfix"></div>
                        </div>
                        <p>
                            تمامی حقوق مادی و معنوی این طرح متعلق به امیرحسین دشتی می باشد.
                        </p>
                    </div>
                </div>
            </div>
        </footer>

        <script src="/Content/js/bootstrap.min.js"></script>
        <script src="/Content/js/owl.carousel.js"></script>
        <script src="/Content/js/script.js"></script>
        @RenderSection("Scripts", false)
</body>
</html>

My_NewsSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap-rtl.css" rel="stylesheet" />
    <link href="https://cdn.rawgit.com/rastikerdar/sahel-font/v1.0.0-alpha23/dist/font-face.css" rel="stylesheet" type="text/css" />
    @*<link href="https://cdn.jsdelivr.net/gh/rastikerdar/sahel-font@v[3.4.0]/dist/font-face.css" rel="stylesheet" type="text/css" />*@

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>